# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys: v1-dependencies-{{ checksum "build.gradle" }}
    - run: gradle dependencies
    - save_cache:
        paths: ~/.m2
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: gradle clean build
    - run: gradle test
    - run: gradle jar
