version: 2

jobs:
  build-test-deploy:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: Build
        command: ./gradlew clean build
    - run:
        name: Test
        command: ./gradlew test
    - store_artifacts:
        path: build/libs/
        destination: artifacts
    - run:
        name: Deploy
        command: |
          sudo apt-get update &&
          sudo apt-get install -qq -y python-pip libpython-dev &&
          curl -O https://bootstrap.pypa.io/get-pip.py &&
          sudo python get-pip.py &&
          sudo pip install -q awscli --upgrade &&
          aws s3 sync build s3://fastcraft/circleci/${CIRCLE_BUILD_NUM} --delete --acl public-read

workflows:
  version: 2
  build-test-deploy:
    jobs:
    - build-test-deploy:
        filters:
          tags:
            only: /.*/
