version: 2

general:
  artifacts:
#  - ~/repo/build/libs/
  - libs/

jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run: gradle dependencies
    - save_cache:
        paths: ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: gradle clean build
    - run: gradle test
    - run: gradle jar

  deploy:
      docker:
      - image: circleci/openjdk:8-jdk
      working_directory: ~/repo
      steps:
      - run: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
      - run: sudo pip install -q awscli --upgrade
      - run: pwd && ls
      - run: aws s3 sync build/libs/ s3://fastcraft/circleci/${CIRCLE_BUILD}/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
