version: 2

jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        description: Build
        command: gradle clean build
    - run:
        description: Test
        command: gradle test
    - store_artifacts:
        path: build/libs
        destination: artifacts
    - run:
        description: Deploy
        command: >
          sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
          curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
          sudo pip install -q awscli --upgrade
          aws s3 sync build/libs s3://fastcraft/circleci/${CIRCLE_BUILD_NUM} --delete --acl public-read
