version: 2

jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
    - checkout
    - run: gradle clean build test
    - store_artifacts:
        path: build/libs
        destination: artifacts

  deploy:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
    - checkout
    - run: gradle jar
    - run: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
    - run: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
    - run: sudo pip install -q awscli --upgrade
    - run: aws s3 sync build/libs s3://fastcraft/circleci/${CIRCLE_BUILD_NUM} --delete

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
