version: 2

jobs:
  build-test-deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew clean build
      - run:
          name: Test
          command: ./gradlew test
      - store_artifacts:
          path: build/libs/
          destination: artifacts

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test-deploy:
          filters:
            tags:
              only: /.*/
