version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys: v1-dependencies-{{ checksum "build.gradle" }}
    - run: gradle dependencies
    - save_cache:
        paths: ~/.m2
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: gradle clean build
    - run: gradle test
    - run: gradle jar

  deploy-job:
      docker:
      - image: circleci/openjdk:8-jdk
      working_directory: ~/repo
      steps:
      - run: aws s3 sync jekyll/_site/docs s3://circle-production-static-site/docs/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
    - build-job
    - deploy-job:
        requires:
        - build-job
        filters:
          branches:
            only:
            - v2/stable
            - v3/stable
