name: "FastCraft"
author: "${plugin_author}"
version: "${plugin_version}"
website: "${plugin_website}"
api-version: "1.13"

description: "${plugin_description}"

main: "net.benwoodworth.fastcraft.bukkit.BukkitFastCraft"

commands:
  fastcraft:
    aliases: [fc]
