name: FastCraft
version: 11
main: me.bw.fastcraft.FastCraft
depend: []
softdepend:
- Vault
- Spout
author: Kepler_
commands:
  fastcraft:
    description: FastCraft commands.
    usage: /<command>
    aliases:
    - fc