name: FastCraft
author: Kepler_
version: 19

description: Improved crafting in Minecraft

main: co.kepler.fastcraft.FastCraft

softdepend: [Vault]

commands:
  fastcraft:
    description: FastCraft commands.
    usage: /fastcraft
    aliases:
    - fc
